<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>no.nav.saf</groupId>
	<artifactId>saf</artifactId>
	<packaging>pom</packaging>
	<version>1-SNAPSHOT</version>
	<modules>
		<module>app</module>
		<module>core</module>
		<module>dokumentoversikt</module>
		<module>graphiql</module>
	</modules>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.1.RELEASE</version>
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<javax.interceptor.version>3.1</javax.interceptor.version>
		<javax.inject.version>1</javax.inject.version>
		<aktoer.version>2.0.1</aktoer.version>
		<cxf.version>3.2.7</cxf.version>
		<graphql-java.version>11.0</graphql-java.version>
		<abac-attribute-constants>3.4.4</abac-attribute-constants>
		<pensjon-sak-v1.version>1.0.1</pensjon-sak-v1.version>
		<rxjava.version>2.2.4</rxjava.version>
		<java-jwt.version>3.4.1</java-jwt.version>
		<logstash-logback-encoder.version>5.2</logstash-logback-encoder.version>
		<logback-syslog4j.version>1.0.0</logback-syslog4j.version>
		<io.springfox.version>2.9.2</io.springfox.version>
		<!-- provided -->
		<lombok.version>1.18.4</lombok.version>
		<!-- test -->
		<junit5.version>5.3.1</junit5.version>
		<junit5.mockito.version>2.23.0</junit5.mockito.version>
		<freg.security.test.version>3.1.0</freg.security.test.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>no.nav.saf</groupId>
				<artifactId>core</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.saf</groupId>
				<artifactId>dokumentoversikt</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.saf</groupId>
				<artifactId>graphiql</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>io.reactivex.rxjava2</groupId>
				<artifactId>rxjava</artifactId>
				<version>${rxjava.version}</version>
			</dependency>
			<dependency>
				<groupId>com.graphql-java</groupId>
				<artifactId>graphql-java</artifactId>
				<version>${graphql-java.version}</version>
			</dependency>
			<dependency>
				<groupId>javax.inject</groupId>
				<artifactId>javax.inject</artifactId>
				<version>${javax.inject.version}</version>
			</dependency>
			<dependency>
				<groupId>javax.interceptor</groupId>
				<artifactId>javax.interceptor-api</artifactId>
				<version>${javax.interceptor.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.tjenester.fim</groupId>
				<artifactId>nav-fim-aktoer-v2-tjenestespesifikasjon</artifactId>
				<version>${aktoer.version}</version>
				<classifier>jaxws</classifier>
			</dependency>
			<dependency>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-spring-boot-starter-jaxws</artifactId>
				<version>${cxf.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-rt-ws-security</artifactId>
				<version>${cxf.version}</version>
			</dependency>
			<dependency>
				<groupId>com.auth0</groupId>
				<artifactId>java-jwt</artifactId>
				<version>${java-jwt.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.sbl</groupId>
				<artifactId>pensjon-sak-v1-tjenestespesifikasjon</artifactId>
				<version>1.0.3</version>
			</dependency>
			<dependency>
				<groupId>no.nav.abac.policies</groupId>
				<artifactId>abac-common-attributes-alfa</artifactId>
				<version>4.0.3</version>
			</dependency>
			<dependency>
				<groupId>no.nav.abac.policies</groupId>
				<artifactId>abac-saf-policies-alfa</artifactId>
				<version>4.1.1</version>
			</dependency>
			<dependency>
				<groupId>net.logstash.logback</groupId>
				<artifactId>logstash-logback-encoder</artifactId>
				<version>${logstash-logback-encoder.version}</version>
			</dependency>
			<dependency>
				<groupId>com.papertrailapp</groupId>
				<artifactId>logback-syslog4j</artifactId>
				<version>${logback-syslog4j.version}</version>
			</dependency>
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>${lombok.version}</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger2</artifactId>
				<version>${io.springfox.version}</version>
			</dependency>
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger-ui</artifactId>
				<version>${io.springfox.version}</version>
			</dependency>
			<dependency>
				<groupId>org.junit.jupiter</groupId>
				<artifactId>junit-jupiter-engine</artifactId>
				<version>${junit5.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.junit.jupiter</groupId>
				<artifactId>junit-jupiter-api</artifactId>
				<version>${junit5.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.mockito</groupId>
				<artifactId>mockito-junit-jupiter</artifactId>
				<version>${junit5.mockito.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-contract-wiremock</artifactId>
				<version>1.2.5.RELEASE</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<artifactId>freg-security-test-oidc-tools</artifactId>
				<groupId>no.nav.freg</groupId>
				<version>${freg.security.test.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>com.github.tomakehurst</groupId>
				<artifactId>wiremock-standalone</artifactId>
				<version>2.19.0</version>
				<scope>test</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
		<extensions>
			<extension>
				<groupId>org.apache.maven.wagon</groupId>
				<artifactId>wagon-webdav-jackrabbit</artifactId>
				<version>1.0</version>
			</extension>
		</extensions>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.22.1</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.22.1</version>
				<configuration>
					<additionalClasspathElements>${basedir}/target/classes</additionalClasspathElements>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<reporting>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-report-plugin</artifactId>
				<version>2.22.1</version>
				<reportSets>
					<reportSet>
						<id>integration-tests</id>
						<reports>
							<report>failsafe-report-only</report>
						</reports>
					</reportSet>
				</reportSets>
			</plugin>
		</plugins>
	</reporting>

</project>

