# ISO-8601 representasjon for en kalenderdato. YYYY-MM-DD. Eksempel: 2018-01-01.
scalar Date

# ISO-8601 representasjon for en kalenderdato med tid, trunkert til nærmeste sekund. YYYY-MM-DD'T'hh:mm:ss. Eksempel: 2018-01-01T12:00:00.
scalar DateTime

schema {
    # Alle spørringer mot SAF GraphQL API.
    query: Query
}

# Query roten til SAF GraphQL API.
type Query {
    # Returnerer dokumentoversikten til en bruker.
    dokumentoversiktBruker(
        # Hent dokumentoversikten til den angitte brukeren.
        brukerId: BrukerIdInput!

         # TODO
        fraDato: Date

        # TODO
        tema: [Tema] = []

        # Velger journalpostene som har de spesifiserte journalposttypene.
        # **Standardverdi**: `I, U, N`
        # TODO legge til default støtte for enum verdier
        journalposttyper: [Journalposttype] = []

        # Velger journalpostene som har de spesifiserte journalstatusene.
        # **Standardverdi**: `FERDIGSTILT, JOURNALFOERT, EKSPEDERT`
        # TODO legge til default støtte for enum verdier
        journalstatuser: [Journalstatus] = []

        # Returnerer de første *n* journalpostene i listen.
        foerste: Int

        # Returnerer journalpostene i listen som kommer etter den angitte pekeren.
        etter: String

        # Returnerer de siste *n* journalpostene i listen.
        siste: Int

        # Returnerer journalpostene i listen som kommer før den angitte pekeren.
        foer: String
    ): Dokumentoversikt!
}

# Dokumentoversikt
type Dokumentoversikt {
    # En liste av journalposter.
    journalposter: [Journalpost]!

    # Informasjon for å hjelpe med paginering.
    sideInfo: SideInfo!
    ): [Journalpost]!

    # Returnerer en liste over alle dokumenter tilknyttet en fagsak.
        dokumentoversiktFagsak(
            # TODO
            fagsakId: String!

            # TODO
            fagsaksystem: String!

            # TODO
            fraDato: Date = null

            # TODO
            tema: [Tema] = []

            # Velger journalpostene som har de spesifiserte journalposttypene
            # **Standardverdi**: `I, U, N`
            # TODO legge til default støtte for enum verdier
            journalposttyper: [Journalposttype] = []

            # Velger journalpostene som har de spesifiserte journalstatusene.
            # **Standardverdi**: `FERDIGSTILT, JOURNALFOERT, EKSPEDERT`
            # TODO legge til default støtte for enum verdier
            journalstatuser: [Journalstatus] = []

            # Returnerer de første *n* journalpostene i listen
            foerste: Int = 30

            # Returnerer journalpostene i listen som kommer etter den angitte pekeren
            etter: String
         ): [Journalpost]!
}

# Informasjon om paginering
type SideInfo {
    # Når man paginerer forover, pekeren for å fortsette.
    sluttpeker: String

    # Når man paginerer forover, finnes det flere sider?
    finnesNesteSide: Boolean!

    # Når man paginerer bakover, pekeren for å fortsette.
    startpeker: String

    # Når man paginerer bakover, finnes det flere sider?
    finnesForrigeSide: Boolean!
}

# Et sett dokumenter som er sendt/mottatt samlet, og har felles arkivmetadata som tema, avsender, arkivsak og sakspart.
# En journalpost kan bestå av ett eller flere dokumenter.
type Journalpost {
    # Identifiserer en Journalpost
    journalpostId: String!

    # TODO
    tittel: String

    # TODO
    journalposttype: Journalposttype

    # TODO
    journalstatus: Journalstatus

    # TODO
    tema: Tema

    # TODO
    temanavn: String

    # TODO
    sak: Sak

    # TODO
    bruker: Bruker

    # TODO
    avsenderMottakerNavn: String

    # TODO
    journalfortAvNavn: String

    # TODO
    kanal: Kanal

    # TODO
    kanalnavn: String

    # TODO
    relevanteDatoer: [RelevantDato]

    # TODO
    dokumenter: [DokumentInfo]
}

# TODO
type RelevantDato {
    # TODO
    dato: DateTime

    # TODO
    datotype: Datotype
}

# TODO
type Sak {
    # TODO
    arkivsaksnummer: String

    # TODO
    arkivsaksystem: Arkivsaksystem

    # TODO
    fagsaknummer: String

    # TODO
    fagsystem: String

    # TODO
    datoOpprettet: DateTime
}

# Person eller organisasjon som har et forhold til NAV, f.eks. som mottaker av tjenester eller ytelser.
type Bruker {
    # TODO
    brukertype: Brukertype

    # TODO
    identifikator: String
}

# TODO
enum Brukertype {
    # TODO
    PERSON

    # TODO
    ORGANISASJON
}

# TODO
type DokumentInfo {
    # TODO
    dokumentId: String!

    # TODO
    tittel: String

    # TODO
    navSkjemaId: String

    # TODO
    saksbehandlerHarTilgang: Boolean

    # TODO
    logiskeVedlegg: [LogiskVedlegg]!

    # TODO
    dokumentvarianter: [Dokumentvariant]!
}

# TODO
type LogiskVedlegg {
    # TODO
    tittel: String
}

# TODO
type Dokumentvariant {
    # TODO
    variantformat: Variantformat
}

# TODO
enum Datotype {
    # TODO
	DATO_OPPRETTET

	# TODO
	DATO_EKSPEDERT

	# TODO
	DATO_MOTTATT

	# TODO
	DATO_SENDT_PRINT

	# TODO
	DATO_JOURNALFOERT
}

# TODO
input BrukerIdInput {
    # TODO
    ident: String!

    # TODO
    identType: BrukerIdInputType!
}

# TODO
enum BrukerIdInputType {
    # Aktørid
    AKTOERID

    # Fødselsnummer
    FNR

    # Organisasjonsnummer
    ORGNR
}

# TODO
enum Arkivsaksystem {
    # TODO
    GSAK

    # TODO
    PSAK
}

# TODO
enum Journalposttype {
    # Inngående dokument
	I

	# Utgående dokument
	U

	# Notat
	N
}

# TODO
enum Journalstatus {
    # TODO
    MOTTATT

    # TODO
    JOURNALFOERT

    # TODO
    FERDIGSTILT

    # TODO
    EKSPEDERT

    # TODO
    UNDER_ARBEID

    # TODO
    FEILREGISTRERT

    # TODO
    UTGAAR

    # TODO
    AVBRUTT

    # TODO
    UKJENT_BRUKER

    # TODO
    RESERVERT

    # TODO
    OPPLASTING_DOKUMENT
}

enum Kanal {
    # Altinn
    ALTINN

    # Utveksling av trygdeinformasjon mellom EU- og EØS-land
	EESSI

	# Elektronisk innsending
	EIA

	# Eksternt oppslag
	EKST_OPPS

	# Lokal utskrift
	LOKAL_UTSKRIFT

	# Ditt NAV
	NAV_NO

	# Selvbetjening Pesys
	PSELV

	# Sentral utskrift
	SENTRAL_UTSKRIFT

	# Sikker Digital Post
	SDP

	# Skanning Nets
	SKAN_NETS

	# Skanning Pensjon
	SKAN_PEN

	# Ingen distribusjon
	INGEN_DISTRIBUSJON
}

enum Tema {
    # Arbeidsavklaringspenger
    AAP

    # Aa-registeret
    AAR

    # Ajourhold - Grunnopplysninger
    AGR

    # Barnetrygd
    BAR

    # Bidrag
    BID

    # Bil
    BIL

    # Dagpenger
    DAG

    # Enslig forsørger
    ENF

    # Erstatning
    ERS

    # Farskap
    FAR

    # Feilutbetaling
    FEI

    # Foreldre- og svangerskapspenger
    FOR

    # Forsikring
    FOS

    # Fullmakt
    FUL

    # Generell
    GEN

    # Gravferdsstønad
    GRA

    # Grunn- og hjelpestønad
    GRU

    # Helsetjenester og ortopediske hjelpemidler
    HEL

    # Hjelpemidler
    HJE

    # Inkluderende arbeidsliv
    IAR

    # Tiltakspenger
    IND

    # Kontakt NAV
    KNA

    # Kontantstøtte
    KON

    # Kontroll
    KTR

    # Medlemskap
    MED

    # Mobilitetsfremmende stønad
    MOB

    # Økonomi
    OKO

    # Omsorgspenger, pleiepenger og opplæringspenger
    OMS

    # Oppfølging - Arbeidsgiver
    OPA

    # Oppfølging
    OPP

    # Pensjon
    PEN

    # Permittering og masseoppsigelser
    PER

    # Rehabilitering
    REH

    # Rekruttering og stilling
    REK

    # Retting av personopplysninger
    RPO

    # Rettferdsvederlag
    RVE

    # Sanksjon - Arbeidsgiver
    SAA

    # Saksomkostninger
    SAK

    # Sanksjon - Person
    SAP

    # Serviceklager
    SER

    # Sikkerhetstiltak
    SIK

    # Regnskap/utbetaling
    STO

    # Supplerende stønad
    SUP

    # Sykepenger
    SYK

    # Sykmeldinger
    SYM

    # Tiltak
    TIL

    # Trekkhåndtering
    TRK

    # Trygdeavgift
    TRY

    # Tilleggsstønad
    TSO

    # Tilleggsstønad arbeidssøkere
    TSR

    # Unntak fra medlemskap
    UFM

    # Uføretrygd
    UFO

    # Ukjent
    UKJ

    # Ventelønn
    VEN

    # Yrkesrettet attføring
    YRA

    # Yrkesskade / Menerstatning
    YRK
}

enum Variantformat {
    # TODO
    ARKIV

    # TODO
    SKJERMET
}