
scalar Date
scalar DateTime

schema {
    query: Query
}

type Query {
    # Returnerer en liste over alle dokumenter tilknyttet en bruker.
    dokumentoversikt(aktoerId: String, fraDato: Date = null, journalposttyper : [Journalposttypekode] = [], journalstatuser : [Journalstatuskode] = [], visFeilregistrerte: Boolean = false): [Journalpost]!
}

type Journalpost {
    journalpostID: String!
    beskrivelse: String
    journalposttype: Journalposttypekode
    journalstatus: Journalstatuskode
    tema: Temakode
    temanavn: String
    sak: Sak
    mottakskanal: String
    opprettet: DateTime
    dokumenter: [DokumentInfo]
}

type Sak {
    arkivsaksnummer: String
    arkivsaksystem: Arkivsaksystemkode
    fagsaknummer: String
    fagsystem: String
    datoOpprettet: DateTime
}

type DokumentInfo {
    dokumentID: String!
    tittel: String
    variantFormat: VariantFormatkode
    saksbehandlerHarTilgang: Boolean
    innbyggerHarDigitaltInnsyn: Boolean
}

enum Arkivsaksystemkode {
    GSAK
    PSAK
}

enum Journalposttypekode {
	I
	U
	N
}

enum Journalstatuskode {
    MIDLERTIDIG
    ENDELIG
    FERDIGSTILT
    EKSPEDERT
    UNDER_ARBEID
    FEILREGISTRERT
    UTGAAR
    AVBRUTT
    UKJENT_BRUKER
}

enum Temakode {
	BID,
	PEN,
	OVR,
	MOT,
	OKO,
	BII,
	BIL,
	HJE,
	BAR,
	FOR,
	GRA,
	GRU,
	KON,
	OMS,
	SUP,
	YRK,
	ENF,
	STO,
	FOS,
	ERS,
	SAK,
	DAG,
	IND,
	MOB,
	OPP,
	VEN,
	YRA,
	REH,
	UFO,
	SYK,
	SYM,
	FEI,
	GEN,
	AAP,
	FUL,
	HEL,
	CON,
	MED,
	UKJ,
	TIL,
	REK,
	IAR,
	AGR,
	TRK,
	KTR,
	PER,
	AAR,
	TRY,
	SAA,
	SAP,
	OPA,
	SER,
	SIK,
	UFM,
	TSR,
	TSO,
	RVE,
	RPO,
	FAR,
}

enum VariantFormatkode {
    ARKIV
    SKJERMET
    SLETTET
}