
scalar Date
scalar DateTime

schema {
    query: Query
}

type Query {
    # Returnerer en liste over alle dokumenter tilknyttet en bruker.
    dokumentoversiktBruker(aktoerId: String, fraDato: Date = null, journalposttyper : [JournalpostType] = [], journalstatuser : [JournalStatus] = []): [Journalpost]!
}

type Journalpost {
    journalpostId: String!
    tittel: String
    journalposttype: JournalpostType
    journalstatus: JournalStatus
    tema: Tema
    temanavn: String
    sak: Sak
    avsenderMottakerNavn: String
    journalfortAvNavn: String
    kanal: Kanal
    kanalnavn: String
    relevanteDatoer: [RelevantDato]
    dokumenter: [DokumentInfo]
}

type RelevantDato {
    dato: DateTime
    datotype: Datotype
}

type Sak {
    arkivsaksnummer: String
    arkivsaksystem: Arkivsaksystem
    fagsaknummer: String
    fagsystem: String
    datoOpprettet: DateTime
}

type DokumentInfo {
    dokumentId: String!
    tittel: String
    navSkjemaId: String
    saksbehandlerHarTilgang: Boolean
    dokumentvarianter: [Dokumentvariant]
}

type Dokumentvariant {
    variantformat: Variantformat
}

enum Datotype {
    OPPRETTET_DATO
    EKSPEDERT_DATO
    MOTTATT_DATO
}

enum Arkivsaksystem {
    GSAK
    PSAK
}

enum JournalpostType {
    # Inngående dokument
	I
	# Utgående dokument
	U
	# Notat
	N
}

enum JournalStatus {
    MIDLERTIDIG_JOURNALFOERT
    MOTTATT
    JOURNALFOERT
    FERDIGSTILT
    EKSPEDERT
    UNDER_ARBEID
    FEILREGISTRERT
    UTGAAR
    AVBRUTT
    UKJENT_BRUKER
    RESERVERT
    OPPLASTING_DOKUMENT
}

enum Kanal {
    ALTINN,
	EESSI,
	EIA,
	EKST_OPPS,
	LOKAL_UTSKRIFT,
	NAV_NO,
	PSELV,
	SENTRAL_UTSKRIFT,
	SDP,
	SKAN_NETS,
	SKAN_PEN
}

enum Tema {
	BID,
	PEN,
	OVR,
	MOT,
	OKO,
	BII,
	BIL,
	HJE,
	BAR,
	FOR,
	GRA,
	GRU,
	KON,
	OMS,
	SUP,
	YRK,
	ENF,
	STO,
	FOS,
	ERS,
	SAK,
	DAG,
	IND,
	MOB,
	OPP,
	VEN,
	YRA,
	REH,
	UFO,
	SYK,
	SYM,
	FEI,
	GEN,
	AAP,
	FUL,
	HEL,
	CON,
	MED,
	UKJ,
	TIL,
	REK,
	IAR,
	AGR,
	TRK,
	KTR,
	PER,
	AAR,
	TRY,
	SAA,
	SAP,
	OPA,
	SER,
	SIK,
	UFM,
	TSR,
	TSO,
	RVE,
	RPO,
	FAR,
}

enum Variantformat {
    ARKIV
    SKJERMET
}