logging.config=classpath:logback-spring.xml
spring.main.banner_mode=off

# actuators
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus
        
graphiql.endpoint=/graphql
server.error.include-message=always
server.tomcat.threads.min-spare=50
server.tomcat.threads.max=150
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

pensjon.v1.readtimeoutms=10000
pensjon.v1.connectiontimeoutms=3000

management.metrics.enable.http.client.requests=false

http.proxy.parametername=notused

# circuitbreaker
resilience4j.circuitbreaker.configs.default.register-health-indicator=true
resilience4j.circuitbreaker.configs.default.sliding-window-size=20
resilience4j.circuitbreaker.configs.default.sliding-window-type=count_based
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=15
resilience4j.circuitbreaker.configs.default.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.configs.default.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=60s
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.default.record-exceptions=no.nav.saf.exceptions.SafTechnicalException,org.springframework.web.client.HttpServerErrorException,java.io.IOException,org.springframework.web.client.ResourceAccessException
resilience4j.circuitbreaker.configs.default.ignore-exceptions=no.nav.saf.exceptions.SafFunctionalException
resilience4j.circuitbreaker.instances.sak.base-config=default
resilience4j.circuitbreaker.instances.pensjonsakrest.base-config=default
resilience4j.circuitbreaker.instances.pensjonsaksoap.base-config=default
resilience4j.circuitbreaker.instances.abac.base-config=default
resilience4j.circuitbreaker.instances.abac.sliding-window-size=100
resilience4j.circuitbreaker.instances.abac.minimum-number-of-calls=75
resilience4j.circuitbreaker.instances.abac.permitted-number-of-calls-in-half-open-state=10
resilience4j.circuitbreaker.instances.joarkhentdokument.base-config=default
resilience4j.circuitbreaker.instances.joarkhentdokument.sliding-window-size=50
resilience4j.circuitbreaker.instances.joarkhentdokument.minimum-number-of-calls=25
resilience4j.circuitbreaker.instances.joarkhentdokument.permitted-number-of-calls-in-half-open-state=5
resilience4j.circuitbreaker.instances.joarkhentdokument.wait-duration-in-open-state=15m
resilience4j.circuitbreaker.instances.pdl.base-config=default
resilience4j.circuitbreaker.instances.k9sak.base-config=default
resilience4j.circuitbreaker.instances.fpsak.base-config=default
resilience4j.circuitbreaker.instances.bidragsak.base-config=default

# retry
resilience4j.retry.configs.default.max-attempts=3
resilience4j.retry.configs.default.wait-duration=500ms
resilience4j.retry.configs.default.enable-exponential-backoff=true
resilience4j.retry.configs.default.exponential-backoff-multiplier=2
resilience4j.retry.configs.default.retry-exceptions=no.nav.saf.exceptions.SafTechnicalException,org.springframework.web.client.HttpServerErrorException,java.io.IOException
resilience4j.retry.configs.default.ignore-exceptions=no.nav.saf.exceptions.SafFunctionalException
resilience4j.retry.instances.sak.base-config=default
resilience4j.retry.instances.pensjonsakrest.base-config=default
resilience4j.retry.instances.pensjonsaksoap.base-config=default
resilience4j.retry.instances.abac.base-config=default
resilience4j.retry.instances.pdl.base-config=default
