#Kommenteres ut ved kjøring av applikasjon på laptop
no.nav.security.jwt.issuer.azurev1.proxy-url=${HTTP_PROXY}
no.nav.security.jwt.issuer.azurev2.proxy-url=${HTTP_PROXY}
no.nav.security.jwt.issuer.azurev2.accepted-audience=${AZURE_APP_CLIENT_ID}
