logging.config=classpath:logback-local.xml
spring.main.banner_mode=off

# actuators
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus

graphiql.endpoint=/graphql
server.tomcat.min-spare-threads=10
server.tomcat.max-threads=50

### Is correct? ###
sak_saker_url=https://sak.nais.preprod.local/api/v1/saker

#### ISSO Agent ###
#security.oidc.host=https://isso-t.adeo.no/isso
#security.openam.username=agentadmin
#security.openam.***passord=gammelt_passord***
#security.openam.redirectUri=https://freg-token-provider.nais.preprod.local/openidconnect
#
#credential.username=srvfreg-token-prov
#credential.***passord=gammelt_passord***

