logging.config=classpath:logback-spring.xml
spring.main.banner_mode=off

# actuators
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus
        
graphiql.endpoint=/graphql
server.tomcat.min-spare-threads=50
server.tomcat.max-threads=200

hentjournalsakinfo.url=https://dokarkiv-q1.nais.preprod.local/hentjournalsakinfo
aktoer.v2.readtimeoutms=10000
aktoer.v2.connectiontimeoutms=3000
sak.saker.url=http://sak/api/v1/saker
pensjonsak.v1.readtimeoutms=10000
pensjonsak.v1.connectiontimeoutms=3000

management.metrics.enable.http.client.requests=false