kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: ABAC_PDP_ENDPOINT_URL
      value: {{ ABAC_PDP_ENDPOINT_URL }}
    - name: SAK_SAKER_URL
      value: {{ SAK_SAKER_URL }}
    - name: K9SAK_URL
      value: {{ K9SAK_URL }}
    - name: SPRINGDOC_ENABLED
      value: "{{ SPRINGDOC_ENABLED }}"
    - name: NO_NAV_SECURITY_JWT_ISSUER_AZUREV2_DISCOVERYURL
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_AZUREV2_DISCOVERYURL }}
    - name: NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_DISCOVERYURL
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_DISCOVERYURL }}
    - name: NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_ACCEPTED_AUDIENCE
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_ACCEPTED_AUDIENCE }}
    - name: SAF_PRIVILEGIEDSERVICEUSERS
      value: {{ SAF_PRIVILEGIEDSERVICEUSERS }}
    - name: SAF_AZURE_GROUP_EGEN_ANSATT_OBJECT_ID
      value: {{ SAF_AZURE_GROUP_EGEN_ANSATT_OBJECT_ID }}
    - name: HENTJOURNALSAKINFO_URL
      value: {{ HENTJOURNALSAKINFO_URL }}
    - name: BIDRAG_SAK_URL
      value: {{ BIDRAG_SAK_URL }}
    - name: SAF_ENDPOINTS_PDL_URL
      value: {{SAF_ENDPOINTS_PDL_URL}}
    - name: SAF_ENDPOINTS_PDL_SCOPE
      value: {{SAF_ENDPOINTS_PDL_SCOPE}}
    - name: SAF_ENDPOINTS_PENSJON_URL
      value: {{SAF_ENDPOINTS_PENSJON_URL}}
    - name: SAF_ENDPOINTS_PENSJON_SCOPE
      value: {{SAF_ENDPOINTS_PENSJON_SCOPE}}
    - name: SAF_ENDPOINTS_DOKARKIV_URL
      value: {{SAF_ENDPOINTS_DOKARKIV_URL}}
    - name: SAF_ENDPOINTS_DOKARKIV_SCOPE
      value: {{SAF_ENDPOINTS_DOKARKIV_SCOPE}}
    - name: SAF_ENDPOINTS_FPSAK_URL
      value: {{SAF_ENDPOINTS_FPSAK_URL}}
    - name: SAF_ENDPOINTS_FPSAK_SCOPE
      value: {{SAF_ENDPOINTS_FPSAK_SCOPE}}
    - name: SAF_ENDPOINTS_HR_NAV_URL
      value: {{SAF_ENDPOINTS_HR_NAV_URL}}
    - name: RESTSECURITYTOKENSERVICE_URL
      value: {{ RESTSECURITYTOKENSERVICE_URL }}
    - name: SAF_REDIS_HOSTNAME
      value: {{ SAF_REDIS_HOSTNAME }}
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "deployment.environment.name={{ ENVIRONMENT }}"
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
    - {{ this }}
    {{/each}}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 2000m
      memory: 2560Mi
    requests:
      memory: 1792Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVSAF }}
        mountPath: "/secrets/serviceuser/srvsaf"
  webproxy: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  accessPolicy:
    inbound:
      rules:
    {{#each AZURE_IAC_RULES}}
        - application: {{app}}
          namespace: {{namespace}}
          cluster: {{cluster}}
          {{#if roles}}
          permissions:
            roles:
              {{#each roles}}
              - "{{this}}"
              {{/each}}
          {{/if}}
    {{/each}}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "elastic-apm"