kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: saf
  namespace: {{ NAMESPACE }}
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: ABAC_PDP_ENDPOINT_URL
      value: {{ ABAC_PDP_ENDPOINT_URL }}
    - name: PENSJONSAKRS_V1_URL
      value: {{ PENSJONSAKRS_V1_URL }}
    - name: SAK_SAKER_URL
      value: {{ SAK_SAKER_URL }}
    - name: SECURITYTOKENSERVICE_URL
      value: {{ SECURITYTOKENSERVICE_URL }}
    - name: PENSJON_V1_ENDPOINTURL
      value: {{ PENSJON_V1_ENDPOINTURL }}
    - name: FPSAK_URL
      value: {{ FPSAK_URL }}
    - name: GRAPHIQL_ENABLED
      value: "{{ GRAPHIQL_ENABLED }}"
    - name: SWAGGER_ENABLED
      value: "{{ SWAGGER_ENABLED }}"
    - name: NO_NAV_SECURITY_JWT_ISSUER_AZUREV1_DISCOVERYURL
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_AZUREV1_DISCOVERYURL }}
    - name: NO_NAV_SECURITY_JWT_ISSUER_AZUREV2_DISCOVERYURL
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_AZUREV2_DISCOVERYURL }}
    - name: NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_DISCOVERYURL
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_DISCOVERYURL }}
    - name: NO_NAV_SECURITY_JWT_ISSUER_OPENAM_DISCOVERYURL
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_OPENAM_DISCOVERYURL }}
    - name: NO_NAV_SECURITY_JWT_ISSUER_AZUREV1_ACCEPTED_AUDIENCE
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_AZUREV1_ACCEPTED_AUDIENCE }}
    - name: NO_NAV_SECURITY_JWT_ISSUER_AZUREV2_ACCEPTED_AUDIENCE
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_AZUREV2_ACCEPTED_AUDIENCE }}
    - name: NO_NAV_SECURITY_JWT_ISSUER_OPENAM_ACCEPTED_AUDIENCE
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_OPENAM_ACCEPTED_AUDIENCE }}
    - name: NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_ACCEPTED_AUDIENCE
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_ACCEPTED_AUDIENCE }}
    - name: SAF_PRIVILEGIEDSERVICEUSERS
      value: {{ SAF_PRIVILEGIEDSERVICEUSERS }}
    - name: HENTJOURNALSAKINFO_URL
      value: {{ HENTJOURNALSAKINFO_URL }}
    - name: BIDRAG_SAK_URL
      value: {{ BIDRAG_SAK_URL }}
    - name: SAF_ENDPOINTS_PDL
      value: {{SAF_ENDPOINTS_PDL}}
    - name: RESTSECURITYTOKENSERVICE_URL
      value: {{ RESTSECURITYTOKENSERVICE_URL }}
    - name: APPD_NAME
      value: {{ APPD_NAME }}
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
    - {{ this }}
    {{/each}}
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: 6
    max: 20
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 2000m
      memory: 2560Mi
    requests:
      memory: 1792Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVSAF }}
        mountPath: "/secrets/serviceuser/srvsaf"
      - kvPath: {{ APPDYNAMICS }}
        mountPath: /var/run/secrets/nais.io/appdynamics
  webproxy: true
