# Manuell instans av saf-redis
# Lagt inn med:
#  kubectl apply -f saf-redis-q1.yaml
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamdokumenthandtering
  annotations:
    nais.io/read-only-file-system: "false"
    nais.io/run-as-user: "999"
  name: saf-redis-q0
  namespace: teamdokumenthandtering
spec:
  image: redis:5-alpine
  port: 6379
  replicas:
    min: 1
    max: 1 # More replicas doesn't sync
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 6379
    protocol: redis